---
sidebar: sidebar 
permalink: rhhc/rhhc-pm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= Solução NetApp com workloads gerenciados da plataforma de contêiner Red Hat OpenShift
:allow-uri-read: 




== Solução NetApp com workloads gerenciados da plataforma de contêiner Red Hat OpenShift

[role="lead"]
Os clientes podem ter "nascido na nuvem" ou estar em um momento da jornada de modernização quando estiverem prontos para mover alguns workloads selecionados ou todos os workloads de seus data centers para a nuvem. Elas podem optar por usar contêineres OpenShift gerenciados por fornecedor e storage de NetApp gerenciado por fornecedor na nuvem para executar seus workloads. Eles devem Planejar e implantar os clusters de contêiner gerenciados do Red Hat OpenShift na nuvem para um ambiente pronto para produção bem-sucedido para suas cargas de trabalho de contêiner. . O NetApp oferece ofertas de storage totalmente gerenciado para soluções gerenciadas da Red Hat em todas as três principais nuvens públicas.

*Amazon FSX for NetApp ONTAP (FSX ONTAP)*

O FSX ONTAP oferece proteção de dados, confiabilidade e flexibilidade para implantações de contêineres na AWS. O Trident serve como o provisionador de armazenamento dinâmico para consumir o armazenamento persistente do FSX ONTAP para aplicações com estado monitorado dos clientes.

Como O ROSA pode ser implantado no modo HA com nós de plano de controle espalhados por várias zonas de disponibilidade, o FSX ONTAP também pode ser provisionado com a opção Multi-AZ, que fornece alta disponibilidade e proteção contra falhas de AZ.

*Google Cloud NetApp volumes*

O Red Hat OpenShift Dedicated é uma plataforma de aplicativos totalmente gerenciada que permite criar, implantar e dimensionar aplicativos rapidamente na nuvem híbrida. O Google Cloud NetApp volumes fornece volumes persistentes, trazendo o pacote completo de recursos de gerenciamento de dados empresariais da ONTAP para implantações do OpenShift no Google Cloud.
