---
sidebar: sidebar 
permalink: data-analytics/sb-4154.html 
keywords:  
summary:  
---
= Análise de dados moderna - soluções diferentes para diferentes estratégias de análise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este white paper descreve as estratégias modernas de soluções de análise de dados da NetApp. Ele inclui detalhes sobre os resultados de negócios, desafios dos clientes, tendências de tecnologia, arquitetura legada da concorrência, workflows modernos, casos de uso, setores, nuvem, parceiros de tecnologia, migradores de dados, consultor digital da NetApp Active IQ (também conhecido como consultor digital), kit de ferramentas de operações de dados da NetApp, Hadoop para Spark, storage definido por software com NetApp Trident Protect, contêineres, gerenciamento de dados empresariais, arquivamento e disposição em camadas para alcançar as metas de IA e análise de dados em camadas e como a NetApp e como a arquitetura de dados estão modernizando juntos.

link:https://www.netapp.com/pdf.html?item=/media/58015-sb-4154.pdf["Análise de dados moderna - soluções diferentes para diferentes estratégias de análise"^]
