---
sidebar: sidebar 
permalink: ehc/ncvs-gc-how-cloud-volumes-service-in-google-cloud-secures-your-data.html 
keywords: secure, architecture, tenancy model, identity management, control plane, security hardening, encryption, zero trust, ransomware 
summary: O Cloud Volumes Service oferece várias maneiras de proteger seus dados de maneira nativa. 
---
= Como o Cloud Volumes Service protege seus dados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O Cloud Volumes Service oferece várias maneiras de proteger seus dados de maneira nativa.



== Arquitetura segura e modelo de alocação

O Cloud Volumes Service fornece uma arquitetura segura no Google Cloud segmentando o gerenciamento de serviços (plano de controle) e o acesso a dados (plano de dados) em diferentes pontos de extremidade para que nenhum deles possa impactar o outro (consulte a seção link:ncvs-gc-cloud-volumes-service-architecture.html[""Arquitetura Cloud Volumes Service""]). Ele usa a estrutura do Google https://cloud.google.com/vpc/docs/private-services-access?hl=en_US["acesso a serviços privados"^] (PSA) para fornecer o serviço. Essa estrutura distingue entre o produtor de serviços, que é fornecido e operado pela NetApp, e o consumidor de serviços, que é uma nuvem privada virtual (VPC) em um projeto de cliente, hospedando os clientes que desejam acessar compartilhamentos de arquivos do Cloud Volumes Service.

Nessa arquitetura, os locatários (veja a link:ncvs-gc-cloud-volumes-service-architecture.html#tenancy-model[""Modelo de alocação""]seção ) são definidos como projetos do Google Cloud completamente isolados uns dos outros, a menos que explicitamente conetados pelo usuário. Os locatários isolam completamente os volumes de dados, os serviços de nomes externos e outros componentes essenciais da solução de outros locatários usando a plataforma de volumes do Cloud Volumes Service. Como a plataforma Cloud Volumes Service está conetada por meio do peering VPC, esse isolamento também se aplica a ela. É possível habilitar o compartilhamento de volumes do Cloud Volumes Service entre vários projetos usando uma VPC compartilhada (consulte a seção link:ncvs-gc-cloud-volumes-service-architecture.html#shared-vpcs[""VPCs compartilhados""]). Você pode aplicar controles de acesso a compartilhamentos SMB e exportações NFS para limitar quem ou o que pode exibir ou modificar conjuntos de dados.



== Gerenciamento de identidade forte para o plano de controle

No plano de controle em que a configuração do Cloud Volumes Service ocorre, o gerenciamento de identidades é gerenciado usando https://cloud.google.com/iam/docs/overview["Gerenciamento de acesso de identidade (IAM)"^]o . O IAM é um serviço padrão que permite controlar autenticação (logins) e autorização (permissões) para instâncias de projeto do Google Cloud. Toda a configuração é realizada com APIs Cloud Volumes Service em um transporte HTTPS seguro usando criptografia TLS 1,2, e a autenticação é realizada usando tokens JWT para maior segurança. A IU do console do Google para Cloud Volumes Service traduz a entrada do usuário em chamadas de API do Cloud Volumes Service.



== Endurecimento de segurança - limitando as superfícies de ataque

Parte da segurança efetiva está limitando o número de superfícies de ataque disponíveis em um serviço. As superfícies de ataque podem incluir várias coisas, incluindo dados em repouso, transferências em trânsito, logins e os próprios conjuntos de dados.

Um serviço gerenciado remove algumas das superfícies de ataque inerentemente em seu design. O gerenciamento da infraestrutura, conforme descrito na seçãolink:ncvs-gc-service-operation.html[""Operação de serviço","], é gerenciado por uma equipe dedicada e automatizado para reduzir o número de vezes que um ser humano realmente toca nas configurações, o que ajuda a reduzir o número de erros intencionais e não intencionais. A rede é vedada para que apenas os serviços necessários possam acessar uns aos outros. A criptografia é integrada ao armazenamento de dados e apenas o plano de dados precisa da atenção de segurança dos administradores do Cloud Volumes Service. Ao ocultar a maior parte do gerenciamento por trás de uma interface API, a segurança é alcançada limitando as superfícies de ataque.



== Modelo Zero Trust

Historicamente, a filosofia de segurança DE TI tem sido confiar, mas verificar, e manifesta-se como confiando apenas em mecanismos externos (como firewalls e sistemas de deteção de intrusão) para mitigar ameaças. No entanto, ataques e violações evoluíram para contornar a verificação em ambientes por meio de phishing, engenharia social, ameaças internas e outros métodos que fornecem a verificação para entrar nas redes e causar estragos.

Zero Trust tornou-se uma nova metodologia em segurança, com o mantra atual sendo "não confie em nada enquanto ainda verifica tudo". Portanto, nada é permitido acessar por padrão. Este mantra é aplicado de várias maneiras, incluindo firewalls padrão e sistemas de deteção de intrusão (IDS) e também com os seguintes métodos:

* Métodos de autenticação fortes (como tokens Kerberos ou JWT criptografados por AES)
* Fontes fortes únicas de identidades (como o Windows ative Directory, LDAP (Lightweight Directory Access Protocol) e Google IAM)
* Segmentação de rede e alocação segura a vários clientes (somente os locatários têm acesso permitido por padrão)
* Controles de acesso granular com políticas de acesso menos privilegiadas
* Pequenas listas exclusivas de administradores dedicados e confiáveis com auditoria digital e trilhas em papel


O Cloud Volumes Service em execução no Google Cloud adere ao modelo de confiança zero ao implementar a postura "não confie nada, verifique tudo".



== Criptografia

Criptografe dados em repouso (consulte a seção link:ncvs-gc-data-encryption-at-rest.html[""Criptografia de dados em repouso""]) usando cifras XTS-AES-256 com criptografia de volume NetApp (NVE) e em trânsito com link:ncvs-gc-data-encryption-in-transit.html#smb-encryption[""Criptografia SMB""]suporte ou NFS Kerberos 5P. Saiba que as transferências de replicação entre regiões são protegidas pela criptografia TLS 1,2 (veja a seção link:ncvs-gc-security-considerations-and-attack-surfaces.html Além disso, a rede do Google também fornece comunicações criptografadas (consulte a seção link:ncvs-gc-data-encryption-in-transit.html[""Criptografia de dados em trânsito""]) para obter uma camada adicional de proteção contra ataques. Para obter mais informações sobre criptografia de transporte, consulte a link:ncvs-gc-data-encryption-in-transit.html#google-cloud-network[""Rede Google Cloud""]seção .



== Proteção de dados e backups

A segurança não se trata apenas da prevenção de ataques. É também sobre como nos recuperamos de ataques se ou quando eles ocorrem. Essa estratégia inclui proteção de dados e backups. O Cloud Volumes Service oferece métodos para replicação para outras regiões em caso de interrupções (consulte a seção link:ncvs-gc-security-considerations-and-attack-surfaces.html#cross-region-replication[""Replicação entre regiões""]) ou se um conjunto de dados for afetado por um ataque de ransomware. Ele também pode executar backups assíncronos de dados para locais fora da instância do Cloud Volumes Service link:ncvs-gc-security-considerations-and-attack-surfaces.html#cloud-volumes-service-backup["Backup Cloud Volumes Service"]usando o . Com backups regulares, a mitigação de eventos de segurança pode levar menos tempo e economizar dinheiro e angústia para os administradores.



== Mitigação rápida de ransomware com cópias Snapshot líderes do setor

Além da proteção de dados e backups, o Cloud Volumes Service fornece suporte para cópias Snapshot imutáveis (consulte a seção link:ncvs-gc-security-considerations-and-attack-surfaces.html#immutable-snapshot-copies[""Cópias Snapshot immutáveis""]) de volumes que permitem recuperação de ataques de ransomware (consulte a seção link:ncvs-gc-service-operation.html[""Operação de serviço""]) em segundos após descobrir o problema e com interrupção mínima. O tempo e os efeitos de recuperação dependem da programação do Snapshot, mas você pode criar cópias Snapshot que fornecem apenas uma hora de deltas em ataques de ransomware. As cópias snapshot têm um efeito insignificante na performance e no uso de capacidade, e são uma abordagem de baixo risco e alta recompensa para proteger seus conjuntos de dados.
