---
sidebar: sidebar 
permalink: ehc/ncvs-gc-service-operation.html 
keywords: physical security, operations team, customer responsibilities, malicious sre protection, certifications, gdpr 
summary: A equipe do Google Cloud NetApp volumes gerencia os serviços de back-end no Google Cloud e usa várias estratégias para proteger a plataforma e impedir o acesso indesejado. 
---
= Operação de manutenção
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A equipe do Google Cloud NetApp volumes gerencia os serviços de back-end no Google Cloud e usa várias estratégias para proteger a plataforma e impedir o acesso indesejado.

Cada cliente recebe sua própria sub-rede exclusiva que tem acesso vedado a outros clientes por padrão, e cada locatário no Google Cloud NetApp volumes obtém seu próprio namespace e VLAN para isolamento total de dados. Depois que um usuário é autenticado, o Service Delivery Engine (SDE) só pode ler dados de configuração específicos para esse locatário.



== Segurança física

Com a pré-aprovação adequada, somente engenheiros no local e engenheiros de suporte de Campo (FSEs) com emblema NetApp têm acesso à gaiola e racks para trabalho físico. Armazenamento e gerenciamento de rede não são permitidos. Somente esses recursos no local podem executar tarefas de manutenção de hardware.

Para engenheiros no local, um ticket é levantado para a declaração de trabalho (SOW) que inclui a ID do rack e a localização do dispositivo (RU) e todos os outros detalhes estão incluídos no ticket. Para os FSEs do NetApp, um bilhete de visita ao site deve ser levantado com o COLO e o bilhete inclui os detalhes, a data e a hora do visitante para fins de auditoria. A SOW para o FSE é comunicada internamente à NetApp.



== Equipe de operações

A equipe de operações do Google Cloud NetApp volumes consiste em engenharia de produção e um engenheiro de confiabilidade do local (SRE) do Google Cloud NetApp volumes e engenheiros de suporte de campo e parceiros da NetApp para hardware. Todos os membros da equipe de operações são credenciados para trabalhar no Google Cloud e Registros detalhados de trabalho são mantidos para cada ticket angariado. Além disso, há um rigoroso controle de mudança e processo de aprovação em vigor para garantir que cada decisão seja devidamente examinada.

A equipe do SRE gerencia o plano de controle e como os dados são roteados de solicitações de IU para hardware e software de back-end no Google Cloud NetApp volumes. A equipe SRE também gerencia recursos do sistema, como máximos de volume e inode. Os SRES não têm permissão para interagir ou ter acesso aos dados do cliente. A SRES também fornece coordenação com as autorizações de devolução de material (RMAs), tais como novas solicitações de substituição de disco ou memória para o hardware de back-end.



== Responsabilidades do cliente

Os clientes do Google Cloud NetApp volumes gerenciam o active Directory e o gerenciamento de funções de usuário da organização, além das operações de volume e dados. Os clientes podem ter funções administrativas e delegar permissões a outros usuários finais dentro do mesmo projeto do Google Cloud usando as duas funções predefinidas que o NetApp e o Google Cloud fornecem (Administrador e Visualizador).

O administrador pode identificar qualquer VPC no projeto do cliente para os volumes do Google Cloud NetApp que o cliente determinar ser apropriado. É responsabilidade do cliente gerenciar o acesso à assinatura do Google Cloud Marketplace e gerenciar os VPCs que têm acesso ao plano de dados.



== Proteção SRE maliciosa

Uma das preocupações que podem surgir é como o Google Cloud NetApp volumes se protege contra cenários em que há um SRE malicioso ou quando as credenciais SRE foram comprometidas?

O acesso ao ambiente de produção é apenas com um número limitado de indivíduos SRE. Os Privileges administrativos estão ainda restritos a um punhado de administradores experientes. Todas as ações executadas por qualquer pessoa no ambiente de produção do Google Cloud NetApp volumes são registradas e quaisquer anomalias na linha de base ou atividades suspeitas são detetadas por nossa plataforma de inteligência de ameaças de gerenciamento de informações de segurança e eventos (SIEM). Como resultado, ações mal-intencionadas podem ser rastreadas e mitigadas antes que muitos danos sejam causados ao back-end do Google Cloud NetApp volumes.



== Ciclo de vida do volume

O Google Cloud NetApp volumes gerencia apenas os objetos dentro do serviço, e não os dados nos volumes. Somente os clientes que acessam os volumes podem gerenciar os dados, as ACLs, os proprietários de arquivos e assim por diante. Os dados nesses volumes são criptografados em repouso, e o acesso é limitado a locatários da instância do Google Cloud NetApp volumes.

O ciclo de vida do volume do Google Cloud NetApp volumes é criar-atualizar-excluir. Os volumes retêm cópias Snapshot de volumes até que os volumes sejam excluídos. Somente os administradores do Google Cloud NetApp volumes validados podem excluir volumes do Google Cloud NetApp volumes. Quando uma exclusão de volume é solicitada por um administrador, é necessária uma etapa adicional de inserir o nome do volume para verificar a exclusão. Depois que um volume é excluído, o volume desaparece e não pode ser recuperado.

Nos casos em que um contrato do Google Cloud NetApp volumes é encerrado, o NetApp marca volumes para exclusão após um período de tempo específico. Antes que esse período de tempo expire, você pode recuperar volumes a pedido do cliente.



== Certificações

Atualmente, o Google Cloud NetApp volumes é certificado de acordo com as normas ISO/IEC 27001:2013 e ISO/IEC 27018:2019. O serviço também recebeu recentemente o seu relatório de atestado de tipo I SOC2. Para obter informações sobre o compromisso da NetApp com a segurança e a privacidade dos dados, https://www.netapp.com/company/trust-center/compliance/["Conformidade: Segurança de dados e privacidade de dados"^] consulte .



== RGPD

Nossos compromissos com a privacidade e o cumprimento do GDPR estão disponíveis em vários de nossos https://www.netapp.com/how-to-buy/sales-terms-and-conditions%22%20/o%20%22SEO%20-%20Sales%20Terms%20and%20Conditions["contratos de clientes"^], como o nosso https://netapp.na1.echosign.com/public/esignWidget?wid=CBFCIBAA3AAABLblqZhCqPPgcufskl_71q-FelD4DHz5EMJVOkqqT0iiORT10DlfZnZeMpDrse5W6K9LEw6o*["Adenda ao Customer Data Processing"^], que inclui o https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en["Cláusulas contratuais padrão"^]fornecido pela Comissão Europeia. Também assumimos esses compromissos em nossa Política de Privacidade, apoiada pelos valores fundamentais estabelecidos em nosso Código de Conduta corporativo.
