---
sidebar: sidebar 
permalink: containers/a-w-n_trident_ontap_nfs.html 
keywords: Trident, Trident, ONTAP, AFF, FAS, NFS 
summary: Para habilitar a integração com o Trident ao sistema de storage NetApp ONTAP, você precisa criar um back-end que permita a comunicação com o sistema de storage. 
---
= Configuração de NFS do NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para habilitar a integração com o Trident ao sistema de storage NetApp ONTAP, você precisa criar um back-end que permita a comunicação com o sistema de storage.

. Há arquivos de back-end de exemplo disponíveis no arquivo de instalação baixado `sample-input` na hierarquia de pastas. Para sistemas NetApp ONTAP que atendem NFS, copie o `backend-ontap-nas.json` arquivo para o diretório de trabalho e edite o arquivo.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/backends-samples/ontap-nas/backend-ontap-nas.json ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi backend-ontap-nas.json
----
. Edite os valores de backendName, managementLIF, dataLIF, svm, nome de usuário e senha neste arquivo.
+
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "ontap-nas+10.61.181.221",
    "managementLIF": "172.21.224.201",
    "dataLIF": "10.61.181.221",
    "svm": "trident_svm",
    "username": "cluster-admin",
    "password": "password"
}
----
+

NOTE: É uma prática recomendada definir o valor backendName personalizado como uma combinação do storageDriverName e do dataLIF que está servindo NFS para fácil identificação.

. Com esse arquivo de back-end instalado, execute o seguinte comando para criar seu primeiro backend.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ ./tridentctl -n trident create backend -f backend-ontap-nas.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| ontap-nas+10.61.181.221 | ontap-nas      | be7a619d-c81d-445c-b80c-5c87a73c5b1e | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. Com o back-end criado, você deve criar uma classe de storage. Assim como no back-end, há um arquivo de classe de armazenamento de amostra que pode ser editado para o ambiente disponível na pasta Sample-inputs. Copie-o para o diretório de trabalho e faça as edições necessárias para refletir o backend criado.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi storage-class-basic.yaml
----
. A única edição que deve ser feita para este arquivo é definir o `backendType` valor para o nome do driver de armazenamento a partir do back-end recém-criado. Observe também o valor name-field, que deve ser referenciado em uma etapa posterior.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
----
+

NOTE: Há um campo opcional chamado `fsType` que é definido neste arquivo. Esta linha pode ser excluída em backends NFS.

. Execute o `kubectl` comando para criar a classe de armazenamento.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Com a classe de storage criada, é necessário criar a primeira reivindicação de volume persistente (PVC). Há um arquivo de exemplo `pvc-basic.yaml` que pode ser usado para executar esta ação localizado em Sample-inputs também.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi pvc-basic.yaml
----
. A única edição que deve ser feita para este arquivo é garantir que o `storageClassName` campo corresponda ao que acabou de criar. A definição de PVC pode ser ainda mais personalizada, conforme exigido pela carga de trabalho a ser provisionada.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Crie o PVC emitindo o `kubectl` comando. A criação pode demorar algum tempo dependendo do tamanho do volume de apoio que está sendo criado, para que você possa assistir ao processo à medida que ele for concluído.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-b4370d37-0fa4-4c17-bd86-94f96c94b42d   1Gi        RWO            basic-csi      7s
----

