---
sidebar: sidebar 
permalink: containers/bmanthos_solution_requirements.html 
keywords: Hardware, software, compute, storage, requirements 
summary: Os recursos independentes de hardware do Anthos em bare metal permitem que você selecione uma plataforma de computação otimizada para o seu caso de uso. Portanto, o pode corresponder à sua infraestrutura existente e reduzir as despesas de capital. 
---
= Requisitos da solução
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Os recursos independentes de hardware do Anthos em bare metal permitem que você selecione uma plataforma de computação otimizada para o seu caso de uso. Portanto, o pode corresponder à sua infraestrutura existente e reduzir as despesas de capital.



== Requisitos de hardware



=== Computação: Traga seu próprio servidor

Os recursos independentes de hardware do Anthos em bare metal permitem que você selecione uma plataforma de computação otimizada para o seu caso de uso. Portanto, o pode corresponder à sua infraestrutura existente e reduzir as despesas de capital.

A tabela a seguir lista o número mínimo de componentes de hardware de computação necessários para implementar essa solução, embora os modelos de hardware usados possam variar de acordo com os requisitos do cliente.

|===
| Utilização | Hardware e modelo | Quantidade 


| Nós de administração | Cisco UCS B200 | 3 


| Nós de trabalho | HP ProLiant DL360 | 4 
|===


=== Armazenamento: NetApp ONTAP

A tabela a seguir lista o número mínimo de componentes de hardware de storage necessários para implementar a solução, embora os modelos de hardware usados possam variar de acordo com os requisitos do cliente.

|===
| Hardware | Modelo | Quantidade 


| NetApp AFF | NetApp AFF A300 | 2 (1 par de HA) 
|===


== Requisitos de software

As versões de software identificadas na tabela a seguir foram usadas pela NetApp e nossos parceiros para validar a solução com o NetApp, embora os componentes de software usados possam variar de acordo com os requisitos do cliente.

|===
| Software | Finalidade | Versão 


| Ubuntu | SO em 3 Admins | 20,04 


|  | SO em Worker4 | 20,04 


|  | SO em Worker3 | 18,04 


| CentOS | SO em Worker2 | 8,2 


| Red Hat Enterprise Linux | SO em Worker1 | 8,1 


| Anthos em bare metal | Orquestração de contêineres | 1.6.0 


| NetApp ONTAP | Armazenamento OS | 9.7P8 


| NetApp Trident | Gerenciamento de storage de contêineres | 20,10 
|===

NOTE: Este ambiente multi-os mostra a interoperabilidade com versões de SO suportadas do Anthos na solução bare metal. Prevemos que os clientes padronizarão em um ou um subconjunto de sistemas operacionais para implantação.

Para Anthos sobre requisitos de hardware e software bare metal, consulte a https://cloud.google.com/anthos/clusters/docs/bare-metal/latest["Anthos na documentação de bare metal"^] página.
