---
sidebar: sidebar 
permalink: containers/rh-os-n_trident_element_iscsi.html 
summary:  
keywords: Trident, Element, Solidfire, iSCSI 
---
= Configuração iSCSI NetApp Element
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para ativar a integração do Trident com o sistema de storage NetApp Element, você deve criar um back-end que permita a comunicação com o sistema de storage usando o protocolo iSCSI.

. Há arquivos de back-end de exemplo disponíveis no arquivo de instalação baixado `sample-input` na hierarquia de pastas. Para sistemas NetApp Element que servem iSCSI, copie o `backend-solidfire.json` ficheiro para o diretório de trabalho e edite o ficheiro.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/backends-samples/solidfire/backend-solidfire.json ./
[netapp-user@rhel7 trident-installer]$ vi ./backend-solidfire.json
----
+
.. Edite o usuário, a senha e o valor MVIP na `EndPoint` linha.
.. Edite o `SVIP` valor.
+
[listing]
----
 {
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://trident:password@172.21.224.150/json-rpc/8.0",
    "SVIP": "10.61.180.200:3260",
    "TenantName": "trident",
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}]
}
----


. Com esse arquivo de back-end instalado, execute o seguinte comando para criar seu primeiro backend.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ ./tridentctl -n trident create backend -f backend-solidfire.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| solidfire_10.61.180.200 | solidfire-san  | b90783ee-e0c9-49af-8d26-3ea87ce2efdf | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. Com o back-end criado, você deve criar uma classe de storage. Assim como no back-end, há um arquivo de classe de armazenamento de amostra que pode ser editado para o ambiente disponível na pasta Sample-inputs. Copie-o para o diretório de trabalho e faça as edições necessárias para refletir o backend criado.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[netapp-user@rhel7 trident-installer]$ vi storage-class-basic.yaml
----
. A única edição que deve ser feita para este arquivo é definir o `backendType` valor para o nome do driver de armazenamento a partir do back-end recém-criado. Observe também o valor name-field, que deve ser referenciado em uma etapa posterior.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "solidfire-san"
----
+

NOTE: Há um campo opcional chamado `fsType` que é definido neste arquivo. Nos backends iSCSI, esse valor pode ser definido para um tipo específico de sistema de arquivos Linux (XFS, ext4, etc.), ou pode ser excluído para permitir que o OpenShift decida qual sistema de arquivos usar.

. Execute o `oc` comando para criar a classe de armazenamento.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Com a classe de storage criada, é necessário criar a primeira reivindicação de volume persistente (PVC). Há um arquivo de exemplo `pvc-basic.yaml` que pode ser usado para executar esta ação localizado em Sample-inputs também.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[netapp-user@rhel7 trident-installer]$ vi pvc-basic.yaml
----
. A única edição que deve ser feita para este arquivo é garantir que o `storageClassName` campo corresponda ao que acabou de criar. A definição de PVC pode ser ainda mais personalizada, conforme exigido pela carga de trabalho a ser provisionada.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Crie o PVC emitindo o `oc` comando. A criação pode demorar algum tempo dependendo do tamanho do volume de apoio que está sendo criado, para que você possa assistir ao processo à medida que ele for concluído.
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[netapp-user@rhel7 trident-installer]$ oc get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-3445b5cc-df24-453d-a1e6-b484e874349d   1Gi        RWO            basic-csi      5s
----

