---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_openshift_virtualization_rosa_prerequisites.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, ROSA, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization 
summary: Red Hat OpenShift Virtualization no ROSA 
---
= Implante o Red Hat OpenShift Virtualization com FSxN no ROSA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta seção fornece detalhes para configurar o FSX for NetApp ONTAP como a Classe de armazenamento padrão para o cluster ROSA e, em seguida, criar uma Máquina Virtual que irá aproveitar o armazenamento FSX ONTAP para seus volumes. Também analisaremos a conexão com a Máquina Virtual usando as credenciais de convidado e reiniciaremos a VM. E, finalmente, realizaremos uma migração ao vivo da Máquina Virtual do nó atual para um novo nó. Examinaremos o conteúdo do armazenamento em disco após a reinicialização de uma VM e a migração em tempo real .



== Pré-requisitos

* link:https://signin.aws.amazon.com/signin?redirect_uri=https://portal.aws.amazon.com/billing/signup/resume&client_id=signup["Conta da AWS"]
* link:https://console.redhat.com/["Uma conta Red Hat"]
* Usuário do IAM link:https://www.rosaworkshop.io/rosa/1-account_setup/["com permissões apropriadas"]para criar e acessar o cluster ROSA
* link:https://aws.amazon.com/cli/["CLI DA AWS"]
* link:https://console.redhat.com/openshift/downloads["ROSA CLI"]
* link:https://console.redhat.com/openshift/downloads["Interface de linha de comando OpenShift"] (oc)
* link:https://docs.aws.amazon.com/eks/latest/userguide/helm.html["Documentação do Helm 3"]
* link:https://docs.openshift.com/rosa/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.html["UM CLUSTER HCP ROSA"] (com pelo menos 3 nós de trabalho bare-metal)
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/virtualization/installing#virt-aws-bm_preparing-cluster-for-virt["OpenShift Virtualization instalado no Rosa Cluster"]
* link:https://console.redhat.com/openshift/overview["Acesso ao console da Web Red Hat OpenShift"]

