---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_use_cases.html 
keywords: Use cases, target audience 
summary: A VDI híbrida com o NetApp VDS permite que fornecedores de serviços e administradores de desktop virtual empresarial expandam facilmente os recursos para outro ambiente de nuvem sem afetar seus usuários. Ter recursos no local no NetApp HCI fornece melhor controle dos recursos de GPU e permite expandir nós de computação ou storage com base na demanda. 
---
= Casos de uso
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A VDI híbrida com o NetApp VDS permite que fornecedores de serviços e administradores de desktop virtual empresarial expandam facilmente os recursos para outro ambiente de nuvem sem afetar seus usuários. Ter recursos locais fornece melhor controle dos recursos e oferece uma ampla seleção de opções (computação, GPU, storage e rede) para atender à demanda.

Esta solução aplica-se aos seguintes casos de uso:

* Expansão da nuvem para picos de demanda por aplicações e desktops remotos
* Reduza o TCO para aplicações e desktops remotos de longa execução hospedando-os no local com recursos de storage flash e GPU
* Facilidade de gerenciamento de aplicações e desktops remotos em ambientes de nuvem
* Experimente desktops e aplicativos remotos usando um modelo de software como serviço com recursos no local




== Público-alvo

O público-alvo da solução inclui os seguintes grupos:

* Arquitetos EUC/VDI que querem entender os requisitos para um VDS híbrido
* Parceiros da NetApp que gostariam de ajudar os clientes com suas necessidades de aplicativos e desktops remotos
* Clientes NetApp HCI existentes que desejam atender às demandas de aplicativos e desktops remotos

