---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_application_management.html 
keywords: tech worker, application, Remote Desktop Services, VDS 
summary: Os trabalhadores de tarefas podem iniciar rapidamente um aplicativo a partir da lista de aplicativos disponibilizados para eles. Os serviços de aplicações publicam aplicações a partir dos anfitriões de sessão dos Serviços de ambiente de trabalho remoto. Com o WVD, os grupos de aplicativos fornecem funcionalidade semelhante a partir de pools de host do Windows 10 de várias sessões. 
---
= Gerenciamento de aplicativos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Os trabalhadores de tarefas podem iniciar rapidamente um aplicativo a partir da lista de aplicativos disponibilizados para eles. Os serviços de aplicações publicam aplicações a partir dos anfitriões de sessão dos Serviços de ambiente de trabalho remoto. Com o WVD, os grupos de aplicativos fornecem funcionalidade semelhante a partir de pools de host do Windows 10 de várias sessões.

Para que os funcionários do escritório possam fornecer usuários avançados, os aplicativos de que eles precisam podem ser provisionados manualmente usando uma placa de serviço ou podem ser provisionados automaticamente usando o recurso de eventos com script no NetApp VDS.

Para obter mais informações, consulte https://docs.netapp.com/us-en/virtual-desktop-service/guide_application_entitlement.html["Página de direitos a aplicativos do NetApp"^] .
