---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_why_ontap.html 
keywords: VDS, Virtual Desktop Service, ONTAP, FlexGroup, File System analytics, cloud tiering, global namespace 
summary: Recursos do ONTAP para o Serviço de desktop virtual. 
---
= Recursos do ONTAP para o Serviço de desktop virtual
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Os seguintes recursos do ONTAP tornam a opção atraente para uso com um serviço de desktop virtual.

* * Sistema de arquivos com escalabilidade horizontal.* Os volumes do ONTAP FlexGroup podem crescer até mais de 20PB TB e conter mais de 400 bilhões de arquivos em um único namespace. O cluster pode conter até 24 nós de storage, cada um com um número flexível de placas de interface de rede, dependendo do modelo usado.
+
Os desktops virtuais do usuário, pastas domésticas, contentores de perfil de usuário, dados compartilhados e assim por diante podem crescer com base na demanda, sem preocupações com limitações de sistema de arquivos.

* *Análise do sistema de arquivos.* Você pode usar a ferramenta XCP para obter insights sobre dados compartilhados. Com o ONTAP 9.8 e o ActiveIQ Unified Manager, é fácil consultar e recuperar informações de metadados de arquivos e identificar dados inativos.
* *Disposição em camadas na nuvem.* Você pode migrar dados inativos para um armazenamento de objetos na nuvem ou para qualquer armazenamento compatível com S3 no seu datacenter.
* *Versões de arquivo.* Os usuários podem recuperar arquivos protegidos por cópias Snapshot do NetApp ONTAP. As cópias Snapshot do ONTAP são muito eficientes em termos de espaço, pois Registram apenas blocos alterados.
* * Namespace global.* A tecnologia ONTAP FlexCache permite o armazenamento em cache remoto de arquivos, facilitando o gerenciamento de dados compartilhados entre locais que contêm sistemas de storage ONTAP.
* *Suporte seguro a vários clientes.* Um único cluster de storage físico pode ser apresentado como vários storage arrays virtuais, cada um com seus próprios volumes, protocolos de storage, interfaces de rede lógicas, domínio de identidade e autenticação, usuários de gerenciamento etc. Portanto, você pode compartilhar o storage array em várias unidades ou ambientes de negócios, como teste, desenvolvimento e produção.
+
Para garantir a performance, use a QoS adaptável para definir níveis de performance com base no espaço usado ou alocado. Além disso, você pode controlar a capacidade de storage usando cotas.

* *Integração com VMware.* As ferramentas do ONTAP para VMware vSphere fornecem um plug-in do vCenter para provisionar armazenamentos de dados, implementar as práticas recomendadas do vSphere host e monitorar os recursos do ONTAP.
+
O ONTAP oferece suporte às APIs de vStorage para integração de array (VAAI) para descarregar operações de arquivos/SCSI para o storage array. O ONTAP também oferece suporte a APIs vStorage for Storage Awareness (VASA) e volumes virtuais para protocolos de bloco e arquivo.

+
O plug-in do SnapCenter para VMware vSphere fornece uma maneira fácil de fazer backup e restaurar máquinas virtuais usando o recurso Snapshot em um storage array.

+
O ActiveIQ Unified Manager fornece visibilidade completa da rede de storage em um ambiente vSphere. Os administradores podem identificar facilmente quaisquer problemas de latência que possam ocorrer em ambientes de desktop virtual hospedados no ONTAP.

* *Conformidade de segurança.* Com o ActiveIQ Unified Manager, você pode monitorar vários sistemas ONTAP com alertas para quaisquer violações de política.
* *Suporte multiprotocolo.* O ONTAP é compatível com protocolos de storage de bloco (iSCSI, FC, FCoE e NVMe/FC), arquivo (NFSv3, NFSv4,1, SMB2.x e SMB3.x) e objeto (S3).
* *Suporte de automação.* O ONTAP fornece módulos API REST, Ansible e PowerShell para automatizar tarefas com o Portal de gerenciamento do VDS.

