---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_nvidia_licensing.html 
keywords: Licensing, NVIDIA, GPU, GRID, Virtual PC 
summary: Ao usar um H610C ou H615C, a licença para a GPU deve ser obtida de parceiros da NVIDIA que estão autorizados a revender as licenças. 
---
= Licenciamento do NVIDIA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ao usar um H610C ou H615C, a licença para a GPU deve ser obtida de parceiros da NVIDIA que estão autorizados a revender as licenças. Você pode encontrar parceiros da NVIDIA com o https://www.nvidia.com/object/partner-locator.html["localizador de parceiros"^]. Procure competências como GPU virtual (vGPU) ou Tesla.

O software vGPU NVIDIA está disponível em quatro edições:

* NVIDIA GRID Virtual PC (REDE VPC)
* Aplicações virtuais NVIDIA GRID (GRID vApps)
* Estação de trabalho Virtual de Data Center NVIDIA Quadro (Quadro vDWS)
* Servidor de computador virtual NVIDIA (vComputeServer)




== GRID Virtual PC

Este produto é ideal para usuários que desejam uma área de trabalho virtual que ofereça uma excelente experiência de usuário para aplicativos, navegadores, vídeo de alta definição e suporte a vários monitores do Microsoft Windows. O NVIDIA GRID Virtual PC oferece uma experiência nativa em um ambiente virtual, permitindo que você execute todos os seus aplicativos de PC com desempenho total.



== Aplicativos virtuais de GRADE

O Grid vApps destina-se a organizações que implantam um Host de sessão de Área de trabalho Remota (RDSH) ou outras soluções de transmissão de aplicativos ou baseadas em sessão. Projetados para fornecer aplicativos do Microsoft Windows com desempenho total, os desktops RDSH hospedados no Windows Server também são suportados pelo Grid vApps.



== Estação de trabalho Virtual Data Center

Esta edição é ideal para designers tradicionais e de alta qualidade que usam poderosos aplicativos de criação de conteúdo 3DD como Dassault CATIA, SOLIDWORKS, 3Dexcite, Siemens NX, PTC Creo, Schlumberger Petrel ou Autodesk Maya. O NVIDIA Quadro vDWS permite que os usuários acessem seus aplicativos gráficos profissionais com todos os recursos e desempenho em qualquer lugar em qualquer dispositivo.



== Servidor de computador virtual NVIDIA

Muitas organizações executam workloads de servidor com uso intenso de computação, como inteligência artificial (AI), deep learning (DL) e ciência de dados. Para esses casos de uso, o software NVIDIA vComputeServer virtualiza a GPU NVIDIA, que acelera as cargas de trabalho de servidor com uso intensivo de computação com recursos como código de correção de erro, remoção de página, peer-to-peer sobre NVLink e multi-vGPU.


NOTE: Uma licença Quadro vDWS permite que você use A VPC DA GRADE e o NVIDIA vComputeServer.
