= 
:allow-uri-read: 


Esta seção descreve as etapas necessárias para configurar os parâmetros na torre AWX/Ansible que preparam o ambiente para o consumo de soluções automatizadas da NetApp.

. Configure o inventário.
+
.. Navegue até recursos → inventários → Adicionar e clique em Adicionar inventário.
.. Forneça detalhes do nome e da organização e clique em Salvar.
.. Na página inventários, clique nos recursos de inventário que você acabou de criar.
.. Se houver variáveis de inventário, cole-as no campo variáveis.
.. Vá para o submenu grupos e clique em Adicionar.
.. Forneça o nome do grupo, copie as variáveis do grupo (se necessário) e clique em Salvar.
.. Clique no grupo criado, vá para o submenu hosts e clique em Adicionar novo host.
.. Forneça o nome do host e o endereço IP do host, cole as variáveis do host (se necessário) e clique em Salvar.


. Criar tipos de credenciais. Para soluções que envolvam ONTAP, Element, VMware ou qualquer outra conexão de transporte baseada em HTTPS, você deve configurar o tipo de credencial para corresponder às entradas de nome de usuário e senha.
+
.. Navegue até Administration → Credential Types e clique em Add (Adicionar).
.. Forneça o nome e a descrição.
.. Cole o seguinte conteúdo na Configuração de Entrada:




[listing]
----
fields:
- id: username
type: string
label: Username
- id: password
type: string
label: Password
secret: true
- id: vsadmin_password
type: string
label: vsadmin_password
secret: true
----
. Cole o seguinte conteúdo na Configuração do injetor:


[listing]
----
extra_vars:
password: '{{ password }}'
username: '{{ username }}'
vsadmin_password: '{{ vsadmin_password }}'
----
. Configurar credenciais.
+
.. Navegue até recursos → credenciais e clique em Adicionar.
.. Introduza o nome e os detalhes da organização.
.. Selecione o tipo de credencial correto; se pretender utilizar o início de sessão SSH padrão, selecione o tipo Máquina ou, em alternativa, selecione o tipo de credencial personalizado que criou.
.. Introduza os outros detalhes correspondentes e clique em Guardar.


. Configure o projeto.
+
.. Navegue até recursos → Projetos e clique em Adicionar.
.. Introduza o nome e os detalhes da organização.
.. Selecione Git para o tipo de credencial de Controle de origem.
.. Cole o URL de controle de origem (ou git clone URL) correspondente à solução específica.
.. Opcionalmente, se o URL Git for controlado pelo acesso, crie e anexe a credencial correspondente na credencial de controle de código-fonte.
.. Clique em Guardar.


. Configure o modelo de trabalho.
+
.. Navegue até recursos → modelos → Adicionar e clique em Adicionar modelo de tarefa.
.. Introduza o nome e a descrição.
.. Selecione o tipo de tarefa; Executar configura o sistema com base em um manual de estratégia e verificar executa uma execução seca do manual de estratégia sem realmente configurar o sistema.
.. Selecione o inventário, o projeto e as credenciais correspondentes para o manual de estratégia.
.. Selecione o manual de estratégia que pretende executar como parte do modelo de tarefa.
.. Normalmente, as variáveis são coladas durante o tempo de execução. Portanto, para obter o prompt para preencher as variáveis durante o tempo de execução, certifique-se de marcar o prompt da caixa de seleção ao iniciar correspondente ao campo variável.
.. Forneça quaisquer outros detalhes conforme necessário e clique em Salvar.


. Inicie o modelo de trabalho.
+
.. Navegue até recursos → modelos.
.. Clique no modelo desejado e, em seguida, clique em Iniciar.
.. Preencha quaisquer variáveis se solicitado no lançamento e clique em Iniciar novamente.



