= Onde ir para ajuda?
:allow-uri-read: 


. Faça login no servidor Oracle como usuário oracle e execute os seguintes comandos:
+
[source, cli]
----
ps -ef | grep ora
----
+

NOTE: Isso listará os processos oracle se a instalação for concluída conforme esperado e o oracle DB for iniciado

. Faça login no banco de dados para verificar as configurações de banco de dados e as PDBs criadas com os seguintes conjuntos de comandos.
+
[source, cli]
----
[oracle@localhost ~]$ sqlplus / as sysdba

SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 12:52:51 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0

SQL>

SQL> select name, log_mode from v$database;
NAME      LOG_MODE
--------- ------------
CDB2      ARCHIVELOG

SQL> show pdbs

    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO

col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;

SQL> col svrname form a30
SQL> col dirname form a30
SQL> select svrname, dirname, nfsversion from v$dnfs_servers;

SVRNAME                        DIRNAME                        NFSVERSION
------------------------------ ------------------------------ ----------------
172.21.126.200                 /rhelora03_u02                 NFSv3.0
172.21.126.200                 /rhelora03_u03                 NFSv3.0
172.21.126.200                 /rhelora03_u01                 NFSv3.0
----
+
Isso confirma que o DNFS está funcionando corretamente.

. Conete-se ao banco de dados via listener para verificar a configuração do listener Hte Oracle com o seguinte comando. Mude para a porta de ouvinte apropriada e nome do serviço de banco de dados.
+
[source, cli]
----
[oracle@localhost ~]$ sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com

SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 13:19:57 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Wed May 05 2021 17:11:11 -04:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0

SQL> show user
USER is "SYSTEM"
SQL> show con_name
CON_NAME
CDB2_PDB1
----
+
Isso confirma que o ouvinte Oracle está funcionando corretamente.





=== Onde ir para ajuda?

Se você precisar de ajuda com o kit de ferramentas, entre no link:https://netapppub.slack.com/archives/C021R4WC0LC["A comunidade de automação de soluções da NetApp oferece suporte ao canal Slack"] e procure o canal de automação de soluções para postar suas perguntas ou perguntas.
