---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-hybrid-multicloud.html 
keywords: vmware, getting, started, overview, netapp, hybrid, multicloud, multi, cloud 
summary:  
---
= Multicloud híbrida
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
As arquiteturas de multicloud híbrida da VMware com NetApp permitem a integração otimizada entre a infraestrutura local e os serviços de nuvem pública, proporcionando flexibilidade e escalabilidade.



== Introdução

Com essa abordagem, as empresas podem migrar workloads com facilidade, otimizar a utilização dos recursos e manter operações consistentes em ambos os ambientes.

Para obter mais informações sobre cenários de nuvem híbrida com VMware e NetApp, link:https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-overview.html#vmware-cloud-options-in-public-cloud["Visão geral da multicloud híbrida da NetApp com a VMware"]consulte .



== Cenários de implantação do VMware com o NetApp

Esta seção descreve várias opções de implantação para ambientes VMware em nuvens locais e públicas. Cada um dos provedores de nuvem oferece suporte a um stack de data center definido por software (SDDC) e/ou VMware Cloud Foundation (VCF) dentro de suas respetivas ofertas de nuvem pública.

* *VMware no local*


O uso do VMware com o storage no local do NetApp fornece um ambiente de virtualização robusto, escalável e flexível. Ao emparelhar os recursos avançados de gerenciamento de dados do NetApp, como deduplicação, compactação e snapshots eficientes, com o sistema de storage apropriado desenvolvido pela ONTAP, os clientes podem escolher a plataforma que funciona para eles. Essa combinação garante alto desempenho, confiabilidade e gerenciamento simplificado para workloads virtualizados, aumentando a eficiência geral do data center.

* *Solução Azure VMware*


O Azure VMware Solution é um serviço de nuvem híbrida que permite o funcionamento total de SDDCs VMware na nuvem pública do Microsoft Azure. A solução VMware do Azure é uma solução de primeira empresa totalmente gerenciada e suportada pela Microsoft, verificada pela VMware utilizando a infraestrutura do Azure. Isso significa que quando a solução VMware Azure é implantada, o cliente obtém o ESXi da VMware para virtualização de computação, o VSAN para armazenamento hiperconvergente e o NSX para rede e segurança, aproveitando a presença global, as instalações de data center líderes de classe do Microsoft Azure e a proximidade com o rico ecossistema de serviços e soluções nativas do Azure.

* *VMware Cloud na AWS*


O VMware Cloud on AWS leva o software SDDC de classe empresarial da VMware para a nuvem AWS, com acesso otimizado a serviços nativos da AWS. Equipado com o VMware Cloud Foundation, o VMware Cloud on AWS integra os produtos de computação, armazenamento e virtualização de rede da VMware (VMware vSphere, VMware VSAN e VMware NSX), juntamente com o gerenciamento do VMware vCenter Server, otimizado para execução em infraestrutura AWS dedicada, elástica e bare-metal.

* *Google Cloud VMware Engine*


O Google Cloud VMware Engine é uma oferta de infraestrutura como serviço (IaaS) desenvolvida com base na infraestrutura escalável de alto desempenho do Google Cloud e na pilha VMware Cloud Foundation – VMware vSphere, vCenter, VSAN e NSX-T. esse serviço permite um caminho rápido para a nuvem, migrando ou estendendo de forma otimizada as cargas de trabalho existentes da VMware de ambientes locais para o Google Cloud Platform sem o custo, esforço ou o risco de rearquitetar aplicações ou reestruturar. É um serviço vendido e suportado pelo Google, trabalhando em estreita colaboração com a VMware.
