---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-bluexp-disaster-recovery.html 
keywords: vmware, getting, started, overview, netapp, bluexp, disaster, recovery, draas 
summary:  
---
= Recuperação de desastres do BlueXP  (DRaaS)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O Planejamento de recuperação de desastres é essencial para que os administradores da VMware minimizem o tempo de inatividade em caso de falhas de hardware, ataques cibernéticos ou desastres naturais.



== Introdução

Ter um plano bem-sucedido e uma combinação de tecnologias garante a proteção de dados críticos, aplicações e VMs. O desafio da DR é determinar o nível apropriado de proteção e os custos associados.

Os arrays ONTAP oferecem replicação incorporada para transferir dados de volume e, portanto, as máquinas virtuais que residem nos LUNs designados do armazenamento de dados, de um local para outro. O BlueXP  DRaaS integra-se ao vSphere e automatiza todo o fluxo de trabalho para failover e failback contínuos em caso de desastre.

Para obter mais informações sobre o BlueXP  DRaaS, link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-overview.html["Visão geral do BlueXP  DRaaS"]consulte .



== Considerações

As partes mais demoradas de um failover de DR em um ambiente VMware vSphere são a execução das etapas necessárias para fazer o inventário, Registrar, reconfigurar e ligar VMs no local de DR. Uma solução ideal tem RPO baixo (medido em minutos) e rto baixo (medido em minutos). Um fator que muitas vezes é negligenciado em uma solução de DR é a capacidade de testar a solução de DR com eficiência em um intervalo periódico.

Para arquitetar uma solução de DR, tenha em mente os seguintes fatores:

* Objetivo de tempo de recuperação (rto). O rto é a rapidez com que uma empresa pode se recuperar de um desastre ou, mais especificamente, quanto tempo leva para executar o processo de recuperação para tornar os serviços de negócios disponíveis novamente.
* Objetivo do ponto de restauração (RPO). O RPO é a idade dos dados recuperados após serem disponibilizados, em relação ao momento em que o desastre ocorreu.
* Escalabilidade e adaptabilidade. Esse fator inclui a capacidade de aumentar os recursos de storage de forma incremental, à medida que a demanda aumenta.


Para obter mais informações técnicas sobre as soluções disponíveis, consulte:

* link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-nfs.html["DR usando o BlueXP  DRaaS para datastores NFS"]
* link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-vmfs.html["DR usando BlueXP  DRaaS para datastores VMFS"]

