---
sidebar: sidebar 
permalink: vmware/vmware-smbc-cvt-smas.html 
keywords: NetApp Solutions, vMSC, Metro Storage Cluster, SnapMirror active sync, Business Continuity, SMBC, ONTAP Tools, AFD, SCV, iSCSI, backup, restore 
summary:  
---
= Converta a sincronização ativa SM de ativo/ativo assimétrico para ativo-ativo simétrico com o VMware vSphere Metro Storage Cluster
:allow-uri-read: 


link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/["NetApp SnapMirror ative Sync (sincronização ativa SM)"] É uma solução robusta para alcançar zero objetivo de tempo de recuperação (rto) e objetivo de ponto de restauração (RPO) em um ambiente virtualizado. link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html["VMware vSphere Metro Storage Cluster (vMSC)"] É uma solução de cluster estendida em diferentes domínios de falha e permite que máquinas virtuais (VMs) sejam distribuídas em dois locais separados geograficamente, fornecendo disponibilidade contínua mesmo que um site falhe. A combinação do vMSC com o SM ative Sync garante a consistência de dados e recursos de failover imediato entre dois locais. Essa configuração é particularmente crucial para aplicações de missão crítica em que qualquer perda de dados ou tempo de inatividade é inaceitável.

O SM active Sync, anteriormente conhecido como SnapMirror Business Continuity (SMBC), permite que os serviços de negócios continuem operando mesmo por meio de uma falha completa no local, dando suporte ao failover de aplicações de forma transparente usando uma cópia secundária. A partir do ONTAP 9.15.1, o SM active Sync é compatível com uma funcionalidade ativo-ativo simétrica. O ativo-ativo simétrico permite operações de e/S de leitura e gravação de ambas as cópias de um LUN protegido com replicação síncrona bidirecional, de modo que ambas as cópias LUN possam servir operações de e/S localmente. Este documento mostra as etapas de como converter SM ative Sync assimétrico ativo/ativo para SM ative Sync simétrica ativo/ativo em um ambiente de cluster VMware Stretch, ou seja, converte uma sincronização SM ativa de uma política de failover automatizado para uma política de failover automatizado-duplex. Para obter detalhes sobre como configurar o vmsc com a sincronização ativa do SnapMirror (SM-as) utilizando o Gerenciador do sistema e as Ferramentas do ONTAP, verifique link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmware-vmsc-with-smas.html["Cluster de armazenamento Metro do VMware vSphere com sincronização ativa do SnapMirror"].



== Pré-requisitos

* Sistemas de storage NetApp: Verifique se você tem dois clusters de storage NetApp (origem e destino) com licenças SnapMirror.
* Conetividade de rede: Verifique a conetividade de rede de baixa latência entre os sistemas de origem e destino.
* Peering de cluster e SVM: Configure o peering de cluster e o peering de Storage Virtual Machine (SVM) entre os clusters de origem e destino.
* Versão do ONTAP: Verifique se ambos os clusters estão executando uma versão do ONTAP compatível com replicação síncrona. Para sincronização ativa SM, é necessário o ONTAP 9.15.1 e posterior.
* Infraestrutura VMware vMSC: Um cluster estendido permite que os subsistemas abranjam geografias, apresentando um conjunto de recursos de infraestrutura base único e comum para o cluster vSphere em ambos os locais. Ele estende a rede e o armazenamento entre os locais.
* Use as ferramentas ONTAP 10,2 em diante para facilidade de uso para NetApp SnapMirror, verifique mais detalhes link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/release-notes/ontap-tools-9-ontap-tools-10-feature-comparison.html["Ferramentas do ONTAP para VMware vSphere 10."]
* Existe uma relação síncrona de SnapMirror com RPO zero entre o cluster primário e o secundário.
* Todos os LUNs no volume de destino devem ser não mapeados antes que a relação zero rto SnapMirror possa ser criada.
* O SnapMirror active Sync só é compatível com protocolos SAN (não NFS/CIFS). Certifique-se de que nenhum componente do grupo de consistência está montado para acesso nas.




== Passos para converter de sincronização ativa SM assimétrica para simétrica

No exemplo abaixo, selectrz1 é o local principal e selectrz2 é o local secundário.

. No site secundário, execute uma atualização do SnapMirror sobre o relacionamento existente.
+
....
selectrz2::> snapmirror update -destination-path site2:/cg/CGsite1_dest
....
. Verifique se a atualização do SnapMirror foi concluída com êxito.
+
....
selectrz2::> snapmirror show
....
. Pausar cada uma das relações síncronas com RPO zero.
+
....
 selectrz2::> snapmirror quiesce -destination-path site2:/cg/CGsite1_dest
....
. Exclua cada uma das relações síncronas com RPO zero.
+
....
selectrz2::> snapmirror delete -destination-path site2:/cg/CGsite1_dest
....
. Libere a relação de origem do SnapMirror, mas mantenha os snapshots comuns.
+
....
selectrz1::> snapmirror release -relationship-info-only  true -destination-path svm0.1:/cg/CGsite1_dest                                           ".
....
. Crie uma relação síncrona de rto SnapMirror zero com a política AutomatedFailoverDuplex.
+
....
selectrz2::> snapmirror create -source-path svm0.1:/cg/CGsite1 -destination-path site2:/cg/CGsite1_dest -cg-item-mappings site1lun1:@site1lun1_dest -policy AutomatedFailOverDuplex
....
. Se os hosts existentes forem locais, o cluster primário, adicione o host ao cluster secundário e estabeleça conetividade com o respetivo acesso a cada cluster.
. No site secundário, exclua os mapas LUN nos grupos associados aos hosts remotos.
+
....
selectrz2::> lun mapping delete -vserver svm0 -igroup wlkd01 -path  /vol/wkld01/wkld01
....
. No local principal, modifique a configuração do iniciador para os hosts existentes para definir o caminho proximal para os iniciadores no cluster local.
+
....
selectrz1::> set -privilege advanced
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1  -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver site1
....
. Adicione um novo grupo e iniciador para os novos hosts e defina a proximidade do host para a afinidade do host para seu site local. Ative a replicação do igroup para replicar a configuração e inverter a localidade do host no cluster remoto.
+
....
selectrz1::*> igroup modify -vserver site1  -igroup smbc2smas -replication-peer svm0.1
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1 -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver svm0.1
....
. Descubra os caminhos nos hosts e verifique se os hosts têm um caminho Ativo/otimizado para o LUN de armazenamento a partir do cluster preferido.
. Implante o aplicativo e distribua as cargas de trabalho da VM entre clusters.
. Ressincronize o grupo de consistência.
+
....
selectrz2::> snapmirror resync -destination-path site2:/cg/CGsite1_dest
....
. Pode novamente hospedar caminhos de e/S LUN para restaurar todos os caminhos para os LUNs.

