---
sidebar: sidebar 
permalink: vmware/vsphere_ontap_auto_block.html 
keywords: vSphere, datastore, VMFS, FC, NVMe/FC, iSER, iSCSI, FCoE,SAN, ONTAP tools 
summary: Esta página fornece etapas para implantar um armazenamento de dados VMFS iSCSI de storage NetApp ONTAP em um ambiente VMware vSphere. 
---
= Provisionamento de storage em bloco tradicional do vSphere com o ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O VMware vSphere oferece suporte às seguintes opções de armazenamento de dados VMFS com suporte ao protocolo SAN ONTAP indicado.

[cols="70%, 30%"]
|===
| Opções do armazenamento de dados VMFS | Suporte ao protocolo SAN ONTAP 


 a| 
link:vsphere_ontap_auto_block_fc.html["Fibre Channel (FC)"]
| sim 


 a| 
link:vsphere_ontap_auto_block_fcoe.html["Fibre Channel over Ethernet (FCoE)"]
| sim 


 a| 
link:vsphere_ontap_auto_block_iscsi.html["ISCSI"]
| sim 


| Extensões iSCSI para RDMA (iSER) | não 


 a| 
link:vsphere_ontap_auto_block_nvmeof.html["NVMe sobre Fabric com FC (NVMe/FC)"]
| sim 


| NVMe sobre Fabric com RDMA em Converged Ethernet (NVMe/RoCE) | não 
|===

NOTE: Se for necessário VMFS iSER ou NVMe/RoCE, verifique os sistemas de storage baseados em SANtricity.
