---
sidebar: sidebar 
permalink: ai/ai-edge-conclusion.html 
keywords: acknowledgements, additional information 
summary: A automação orientada por IA e a computação de borda são uma abordagem líder para ajudar as organizações empresariais a alcançar a transformação digital e maximizar a eficiência operacional e a segurança. Com a computação de borda, os dados são processados muito mais rápido, porque não precisam viajar de e para um data center. Portanto, o custo associado ao envio de dados para data centers ou para a nuvem é reduzido. 
---
= Conclusão
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A automação orientada por IA e a computação de borda são uma abordagem líder para ajudar as organizações empresariais a alcançar a transformação digital e maximizar a eficiência operacional e a segurança. Com a computação de borda, os dados são processados muito mais rápido, porque não precisam viajar de e para um data center. Portanto, o custo associado ao envio de dados para data centers ou para a nuvem é reduzido. A menor latência e o aumento da velocidade podem ser benéficos quando as empresas precisam tomar decisões em tempo quase real usando modelos de inferência de IA implantados na borda.

Os sistemas de storage da NetApp oferecem a mesma ou melhor performance do storage SSD local e oferecem os seguintes benefícios para cientistas de dados, engenheiros de dados, desenvolvedores de AI/ML e responsáveis por decisões DE negócios ou TI:

* Compartilhamento fácil de dados entre sistemas de AI, análises e outros sistemas empresariais essenciais. Esse compartilhamento de dados reduz a sobrecarga da infraestrutura, melhora a performance e otimiza o gerenciamento de dados em toda a empresa.
* Computação e storage escaláveis de forma independente para minimizar custos e melhorar a utilização dos recursos.
* Workflows de desenvolvimento e implantação otimizados usando clones e cópias Snapshot integrados para espaços de trabalho de usuário instantâneos e com uso eficiente de espaço, controle de versão integrado e implantação automatizada.
* Proteção de dados de nível empresarial para recuperação de desastres e continuidade dos negócios. A solução NetApp e Lenovo apresentada neste documento é uma arquitetura flexível e com escalabilidade horizontal ideal para implantações de inferência de IA de nível empresarial na borda.




== Agradecimentos

* J.J. Falkanger, gerente sênior, soluções de HPC e AI, Lenovo
* Dave Arnette, engenheiro técnico de marketing, NetApp
* Joey Parnell, líder de tecnologia e-Series AI Solutions, NetApp
* Cody Harryman, Engenheiro de QA, NetApp




== Onde encontrar informações adicionais

Para saber mais sobre as informações descritas neste documento, consulte os seguintes documentos e/ou sites:

* Página de produto arrays da série A do NetApp AFF
+
https://www.netapp.com/data-storage/aff-a-series/["https://www.netapp.com/data-storage/aff-a-series/"^]

* Software de gerenciamento de dados NetApp ONTAP: Biblioteca de informações ONTAP 9
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* TR-4727: Introdução à EF-Series da NetApp
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf"^]

* Folha de dados do software NetApp e-Series SANtricity
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf["https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf"^]

* Storage persistente do NetApp para contêineres: NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* MLPerf
+
** https://mlcommons.org/en/["https://mlcommons.org/en/"^]
** http://www.image-net.org/["http://www.image-net.org/"^]
** https://mlcommons.org/en/news/mlperf-inference-v11/["https://mlcommons.org/en/news/mlperf-inference-v11/"^]


* Cópia e sincronização do NetApp BlueXP 
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* Benchmark TensorFlow
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* Lenovo ThinkSystem SE350 Edge Server
+
https://lenovopress.com/lp1168["https://lenovopress.com/lp1168"^]

* Lenovo ThinkSystem DM5100F Unified Flash Storage Array
+
https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array["https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array"]


