---
sidebar: sidebar 
permalink: ai/ai-protopia-where-to-find-additional-information-acknowledgements-and-version-history.html 
keywords:  
summary:  
---
= Onde encontrar informações adicionais e agradecimentos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para saber mais sobre as informações descritas neste documento, consulte os seguintes documentos e/ou sites:

* Software de gerenciamento de dados NetApp ONTAP: Biblioteca de informações ONTAP
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* Storage persistente do NetApp para contêineres: NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* Toolkit DataOps do NetApp
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* Storage persistente do NetApp para contêineres: NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* Protopia AI – inferência confidencial
+
https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/["https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/"^]

* Cópia e sincronização do NetApp BlueXP 
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* Servidor de inferência NVIDIA Triton
+
https://developer.nvidia.com/nvidia-triton-inference-server["https://developer.nvidia.com/nvidia-triton-inference-server"^]

* Documentação do servidor de inferência NVIDIA Triton
+
https://docs.nvidia.com/deeplearning/triton-inference-server/index.html["https://docs.nvidia.com/deeplearning/triton-inference-server/index.html"^]

* FaceBoxes em PyTorch
+
https://github.com/zisianw/FaceBoxes.PyTorch["https://github.com/zisianw/FaceBoxes.PyTorch"^]





== Agradecimentos

* Mark Cates, diretor de produto, NetApp
* Sufian Ahmad, Engenheiro de Marketing Técnico, NetApp
* Hadi Esmaeilzadeh, Diretor de tecnologia e Professor, Protopia AI

