---
sidebar: sidebar 
permalink: ai/aks-anf_set_up_dask_with_rapids_deployment_on_aks_using_helm.html 
keywords: dask, rapids, deployment, aks, helm, pvc, persistent volume claim 
summary: Esta página descreve a configuração do Dask com A implantação do RAPIDS no AKS usando o Helm. 
---
= Configure o Dask com a implantação DO RAPIDS no AKS usando o Helm
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para configurar o Dask com A implantação DO RAPIDS no AKS usando o Helm, execute as seguintes etapas:

. Crie um namespace para instalar o Dask com RAPIDS.
+
....
kubectl create namespace rapids-dask
....
. Crie um PVC para armazenar o conjunto de dados de taxa de cliques:
+
.. Salve o seguinte conteúdo YAML em um arquivo para criar um PVC.
+
....
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-criteo-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: azurenetappfiles
....
.. Aplique o arquivo YAML ao cluster do Kubernetes.
+
....
kubectl -n rapids-dask apply -f <your yaml file>
....


. Clonar o `rapidsai git` repositório ( https://github.com/rapidsai/helm-chart["https://github.com/rapidsai/helm-chart"^] ).
+
....
git clone https://github.com/rapidsai/helm-chart helm-chart
....
. Modifique `values.yaml` e inclua o PVC criado anteriormente para workers e o workspace Jupyter.
+
.. Vá para `rapidsai` o diretório do repositório.
+
....
cd helm-chart/rapidsai
....
.. Atualize o `values.yaml` arquivo e monte o volume usando PVC.
+
....
dask:
  …
  worker:
    name: worker
    …
    mounts:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-criteo-data
      volumeMounts:
        - name: data
          mountPath: /data
    …
  jupyter:
    name: jupyter
    …
    mounts:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-criteo-data
      volumeMounts:
        - name: data
          mountPath: /data
    …
....


. Vá para o diretório inicial do repositório e implante o Dask com três nós de trabalho no AKS usando o Helm.
+
....
cd ..
helm dep update rapidsai
helm install rapids-dask --namespace rapids-dask rapidsai
....

