---
sidebar: sidebar 
permalink: ai/mlrun_where_to_find_additional_information.html 
keywords: NetApp Find Additional Information 
summary:  
---
= Onde encontrar informações adicionais
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para saber mais sobre as informações descritas neste documento, consulte os seguintes recursos:

* Storage persistente do NetApp para contêineres:
+
** NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]



* Estrutura e ferramentas DO ML:
+
** TensorFlow: Uma estrutura de aprendizado de máquina de código aberto para todos https://www.tensorflow.org/["https://www.tensorflow.org/"^]
** Docker
+
https://docs.docker.com["https://docs.docker.com"^]

** Kubernetes
+
https://kubernetes.io/docs/home/["https://kubernetes.io/docs/home/"^]

** Kubeflow
+
http://www.kubeflow.org/["http://www.kubeflow.org/"^]

** Servidor de notebook Jupyter
+
http://www.jupyter.org/["http://www.jupyter.org/"^]



* Iguazio Data Science Platform
+
** Documentação da Plataforma de Ciência de dados Iguazio
+
https://www.iguazio.com/docs/["https://www.iguazio.com/docs/"^]

** Função Nuclio sem servidor
+
https://nuclio.io/["https://nuclio.io/"^]

** Estrutura de orquestração de pipeline opensource MLRun
+
https://www.iguazio.com/open-source/mlrun/["https://www.iguazio.com/open-source/mlrun/"^]



* Sistemas NVIDIA DGX-1
+
** Sistemas NVIDIA DGX-1
+
https://www.nvidia.com/en-us/data-center/dgx-1/["https://www.nvidia.com/en-us/data-center/dgx-1/"^]

** NVIDIA GPU NVIDIA Tesla V100
+
https://www.nvidia.com/en-us/data-center/tesla-v100/["https://www.nvidia.com/en-us/data-center/tesla-v100/"^]

** Nuvem de GPU da NVIDIA
+
https://www.nvidia.com/en-us/gpu-cloud/["https://www.nvidia.com/en-us/gpu-cloud/"^]



* Sistemas NetApp AFF
+
** Vantagem de flash do NetApp para AFF
+
https://www.netapp.com/pdf.html?item=/media/19894-ds-3733.pdf["https://www.netapp.com/us/media/ds-3733.pdf"^]

** Documentação do ONTAP 9.x
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

** Relatório técnico da NetApp FlexGroup
+
https://www.netapp.com/pdf.html?item=/media/7337-tr4557pdf.pdf["https://www.netapp.com/us/media/tr-4557.pdf"^]



* NetApp ONTAP AI
+
** ONTAP AI com DGX-1 e Guia de design de rede da Cisco
+
https://www.netapp.com/us/media/nva-1121-design.pdf["https://www.netapp.com/us/media/nva-1121-design.pdf"^]

** ONTAP AI com DGX-1 e Guia de implantação de redes Cisco
+
https://www.netapp.com/pdf.html?item=/media/7677-nva1121designpdf.pdf["https://www.netapp.com/us/media/nva-1121-deploy.pdf"^]

** ONTAP AI com DGX-1 e Guia de design de rede Mellanox
+
https://www.netapp.com/pdf.html?item=/media/17122-nva1138designpdf.pdf["https://www.netapp.com/us/media/nva-1138-design.pdf"^]



* Rede de IA da ONTAP
+
** Switches Cisco Nexus 3232C Series
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html["https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html"^]

** Série de switches Ethernet Mellanox Scale-out SN2000
+
https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000["https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000"^]




