---
sidebar: sidebar 
permalink: ai/nva-1153-design.html 
keywords:  
summary:  
---
= DESIGN de NVA-1153: NetApp ONTAP AI com sistemas NVIDIA DGX A100 e switches Ethernet de espetro Mellanox
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


NetApp e Shiloh

[role="lead"]
O DESIGN do NVA-1153 descreve uma arquitetura verificada da NetApp para workloads de aprendizado de máquina (ML) e inteligência artificial (AI) usando os sistemas de storage da NetApp AFF A800, os sistemas NVIDIA DGX A100 e os switches Ethernet NVIDIA Mellanox Spectrum SN3700V 200GB. Esse design apresenta RDMA sobre Converged Ethernet (RoCE) para a malha de interconexão de cluster de computação, para fornecer aos clientes uma arquitetura totalmente baseada em ethernet para workloads de alto desempenho. Este documento também inclui resultados de teste de benchmark para a arquitetura conforme implementado.

link:https://www.netapp.com/pdf.html?item=/media/21793-nva-1153-design.pdf["DESIGN de NVA-1153: NetApp ONTAP AI com sistemas NVIDIA DGX A100 e switches Ethernet de espetro Mellanox"^]
