---
sidebar: sidebar 
permalink: ai/nva-1156-design.html 
keywords:  
summary:  
---
= DESIGN de NVA-1156: NetApp EF-Series AI com sistemas NVIDIA DGX A100 e BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Abdel Sadek, Tim Chau, Joe McCormick e David Arnette, NetApp

[role="lead"]
O DESIGN do NVA-1156 descreve uma arquitetura verificada do NetApp para workloads de aprendizado de máquina (ML) e inteligência artificial (AI) usando os sistemas de storage NVMe NetApp EF600, o sistema de arquivos paralelos do BeeGFS, os sistemas NVIDIA DGX A100 e os switches NVIDIA Mellanox Quantum QM8700 200Gbps IB. Esse design conta com InfiniBand de 200Gbps GB (IB) para a malha de interconexão de cluster de computação e storage, a fim de fornecer aos clientes uma arquitetura totalmente baseada em IB para workloads de alto desempenho. Este documento também inclui resultados de teste de benchmark para a arquitetura conforme implementado.

link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["DESIGN de NVA-1156: NetApp EF-Series AI com sistemas NVIDIA DGX A100 e BeeGFS"^]
