---
sidebar: sidebar 
permalink: ai/osrunai_netapp_ontap_ai_and_ai_control_plane.html 
keywords:  
summary:  
---
= Plano de controle de AI e AI do NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A arquitetura do NetApp ONTAP AI é baseada nos sistemas DGX da NVIDIA e nos sistemas de storage conectados à nuvem da NetApp. Essa arquitetura de referência oferece às ORGANIZAÇÕES DE TI as seguintes vantagens:

* Elimina complexidades de design
* Possibilita o dimensionamento independente da computação e do storage
* Permite que os clientes comecem aos poucos e escalem de forma otimizada
* Oferece diversas opções de storage para diversos fins de performance e custo-benefício, o NetApp ONTAP AI integra diretamente os sistemas DGX e os sistemas de storage da NetApp AFF A800 com uma rede de última geração. Os sistemas NetApp ONTAP AI e DGX simplificam as implantações de AI eliminando a complexidade do design e as suposições. Os clientes podem começar aos poucos e expandir seus sistemas de maneira ininterrupta, além de gerenciar dados de forma inteligente da borda para o centro e para a nuvem e vice-versa.


O NetApp AI Control Plane é uma solução de gerenciamento de experimentos e dados de AI, ML e deep learning (DL) para cientistas de dados e engenheiros de dados. À medida que as organizações aumentam o uso da AI, elas enfrentam muitos desafios, incluindo escalabilidade de workload e disponibilidade de dados. O plano de controle de IA do NetApp aborda esses desafios por meio de funcionalidades, como clonar rapidamente um namespace de dados, assim como um repositório Git e definir e implementar fluxos de trabalho de treinamento de IA que incorporam a criação quase instantânea de dados e linhas de base de modelo para rastreabilidade e controle de versão. Com o plano de controle do NetApp AI, você replica dados de forma otimizada em locais e regiões e provisiona rapidamente espaços de trabalho do Jupyter notebook com acesso a conjuntos de dados massivos.
